name: test-run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download Allure History
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: allure-history
          path: allure-history

      - name: Copy Allure History to Allure Results, if available
        run: |
          if [ -d allure-history ]; then 
            mkdir -p allure-results
            cp -r allure-history allure-results/history
          fi

      - name: Build and test with Maven
        run: mvn -B clean test -DsuiteXmlFile=src/test/resources/runners/TestNG_AllApiTests.xml

      - name: Install Allure CLI
        run: |
          sudo npm install -g allure-commandline --unsafe-perm=true

      - name: Create Allure environment properties
        run: |
          echo "Environment=QA" > allure-results/environment.properties
          echo "BaseUrl=https://automationexercise.com/api/" >> allure-results/environment.properties

      - name: Set Allure executor info
        run: |
          echo '{
            "name": "GitHub Actions",
            "type": "github",
            "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "buildOrder": ${{ github.run_number }},
            "buildName": "Workflow #${{ github.run_number }}",
            "buildUrl": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "reportUrl": "",
            "executor": "GitHub Actions"
          }' > allure-results/executor.json

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure History
        uses: actions/upload-artifact@v4
        with:
          name: allure-history
          path: allure-report/history

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          force_orphan: true
